name: Notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deployment"]
    types:
      - completed


jobs:

  notify_failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Notify Discord
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          webhook-url: ${{ secrets.NOTIFY_WEBHOOK }}
          content: "${{github.repository}}\n\n**${{github.event.workflow_run.name}} successfull**\n\n${{ github.event.workflow_run.head_commit.message }}"
      - name: Notify Discord
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          webhook-url: ${{ secrets.NOTIFY_WEBHOOK }}
          content: "${{github.repository}}\n\n**${{github.event.workflow_run.name}} failed**\n\n${{ github.event.workflow_run.head_commit.message }}"
